issues:
  exclude-use-default: false
linters:
  enable-all: true
  disable:
    - nosnakecase
    - paralleltest
    - golint
    - maligned
    - scopelint
    - varcheck
    - interfacer
    - ifshort
    - exhaustivestruct
    - exhaustruct
    - structcheck
    - deadcode
    - gofumpt
    - wsl
    - godox
    - gomnd
    - ireturn
    - testpackage
linters-settings:
  stylecheck:
    checks: ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022"]
  revive:
    rules:
      - name: var-naming
        disabled: true
      - name: exported
        disabled: false
