version: "2"
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - godox
    - inamedparam
    - ireturn
    - paralleltest
    - testpackage
    - wsl
  settings:
    revive:
      rules:
        - name: exported
          disabled: false
    staticcheck:
      checks:
        - all
        - -ST1000
  exclusions:
    generated: lax
    rules:
      - linters:
          - funlen
          - gosec
        path: (.+)_test.go
      - linters:
          - mnd
        path: ^internal/options/
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
