issues:
  exclude-use-default: false
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - funlen
        - gosec
    - path: ^internal/options/
      linters:
        - mnd
linters:
  enable-all: true
  disable:
    - depguard
    - exhaustruct
    - godox
    - gofumpt
    - ireturn
    - paralleltest
    - tenv
    - testpackage
    - wsl
linters-settings:
  stylecheck:
    checks: ["all", "-ST1000"]
  revive:
    rules:
      - name: exported
        disabled: false
