issues:
  exclude-use-default: false
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - funlen
        - gosec
linters:
  enable-all: true
  disable:
    - deadcode
    - depguard
    - exhaustivestruct
    - exhaustruct
    - godox
    - gofumpt
    - golint
    - ifshort
    - interfacer
    - ireturn
    - maligned
    - nosnakecase
    - paralleltest
    - scopelint
    - structcheck
    - testpackage
    - varcheck
    - wsl
linters-settings:
  stylecheck:
    checks: ["all", "-ST1000"]
  revive:
    rules:
      - name: exported
        disabled: false
