# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_install_hook_types:
- pre-commit
- pre-push
default_stages:
- pre-commit
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
    exclude: ^charts/kube-transition-metrics/templates/
  - id: check-added-large-files
- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.5.1
  hooks:
  - id: go-fmt
  - id: golangci-lint
    args:
    - --timeout=5m
  - id: go-mod-tidy
- repo: local
  hooks:
    - id: json-schema-for-humans
      name: json-schema-for-humans
      description: Generate doc/SCHEMA.md with https://github.com/coveooss/json-schema-for-humans
      entry: bash -c 'python -m venv .venv && source .venv/bin/activate && pip install --quiet json-schema-for-humans && generate-schema-doc --config-file .jsfh-conf.yaml internal/logging/schemas doc/SCHEMA.md'
      language: system
      files: internal/logging/schemas
      types:
      - json
- repo: local
  hooks:
  - id: trufflehog
    name: TruffleHog
    description: Detect secrets in your data.
    entry: bash -c 'docker run --rm -v "$PWD:/src" ghcr.io/trufflesecurity/trufflehog:latest git --branch=HEAD file:///src --fail --only-verified'
    language: system
    stages:
    - pre-push
- repo: local
  hooks:
  - id: semgrep
    name: semgrep
    entry: bash -c 'docker run --rm -v "$PWD:/src" returntocorp/semgrep semgrep --config p/ci --error --skip-unknown-extensions'
    language: system
    stages:
    - pre-push
