{{- if .Values.role.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-transition-metrics.clusterRoleName" .  | quote }}
  labels:
    {{- include "kube-transition-metrics.labels" . | nindent 4 }}
  annotations:
    {{- include "kube-transition-metrics.annotations" . | nindent 4 }}
    {{- with .Values.role.annotations }}
    {{-   toYaml . | nindent 4 }}
    {{- end }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - events
  verbs:
  - list
  - watch
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kube-transition-metrics.clusterRoleBindingName" . | quote }}
  labels:
    {{- include "kube-transition-metrics.labels" . | nindent 4 }}
  {{- with .Values.role.binding.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kube-transition-metrics.clusterRoleName" . | quote }}
subjects:
- kind: ServiceAccount
  name: {{ include "kube-transition-metrics.serviceAccountName" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
{{- end }}
