name: Release Helm chart

on:
  push:
    branches:
      - main

jobs:
  helm:
    name: Helm
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
            fetch-depth: 0

      - name: Configure Git
        run: |
            git config user.name "$GITHUB_ACTOR"
            git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
            CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
