---
name: pre-commit

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - uses: golangci/golangci-lint-action@v9
        with:
          version: v2.11.3
          install-only: true

      - uses: pre-commit/action@v3.0.1
        env:
          # The official golangci-lint action runs config verification and linter, but does not run the formatter.
          SKIP: golangci-lint-config-verify,golangci-lint-full
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
