name: pre-commit

on:
  pull_request:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4.4.0
        with:
          python-version: '3.x'

      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libdevmapper-dev libbtrfs-dev

      - uses: pre-commit/action@646c83fcd040023954eafda54b4db0192ce70507
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
