---
name: Go build and test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Build
        run: make buildable

      - name: Test Unit
        run: make test-unit

      - name: Run testable examples
        run: make test-examples

      - name: Benchmark
        run: make benchmark

      - name: Test flakiness
        run: make test-flakiness
